/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdicionalOutput } from '../../models/adicional-output';

export interface Buscar4$Params {
  id: number;
}

export function buscar4(http: HttpClient, rootUrl: string, params: Buscar4$Params, context?: HttpContext): Observable<StrictHttpResponse<AdicionalOutput>> {
  const rb = new RequestBuilder(rootUrl, buscar4.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/problem+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdicionalOutput>;
    })
  );
}

buscar4.PATH = '/api/adicionais/{id}';
