/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdicionalInput } from '../../models/adicional-input';
import { AdicionalOutput } from '../../models/adicional-output';

export interface Criar5$Params {
      body: AdicionalInput
}

export function criar5(http: HttpClient, rootUrl: string, params: Criar5$Params, context?: HttpContext): Observable<StrictHttpResponse<AdicionalOutput>> {
  const rb = new RequestBuilder(rootUrl, criar5.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/problem+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdicionalOutput>;
    })
  );
}

criar5.PATH = '/api/adicionais';
