/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClienteOutput } from '../../models/cliente-output';

export interface Listar2$Params {
}

export function listar2(http: HttpClient, rootUrl: string, params?: Listar2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClienteOutput>>> {
  const rb = new RequestBuilder(rootUrl, listar2.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClienteOutput>>;
    })
  );
}

listar2.PATH = '/api/clientes';
