/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DesativarOpcao$Params {

/**
 * ID da categoria
 */
  idCategoria: number;

/**
 * ID da opcao
 */
  idOpcao: number;
}

export function desativarOpcao(http: HttpClient, rootUrl: string, params: DesativarOpcao$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, desativarOpcao.PATH, 'delete');
  if (params) {
    rb.path('idCategoria', params.idCategoria, {});
    rb.path('idOpcao', params.idOpcao, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

desativarOpcao.PATH = '/api/categorias/{idCategoria}/opcoes/{idOpcao}';
