/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaOpcaoOutput } from '../../models/categoria-opcao-output';

export interface ListarOpcoes$Params {

/**
 * ID da categoria
 */
  idCategoria: number;
}

export function listarOpcoes(http: HttpClient, rootUrl: string, params: ListarOpcoes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoriaOpcaoOutput>>> {
  const rb = new RequestBuilder(rootUrl, listarOpcoes.PATH, 'get');
  if (params) {
    rb.path('idCategoria', params.idCategoria, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoriaOpcaoOutput>>;
    })
  );
}

listarOpcoes.PATH = '/api/categorias/{idCategoria}/opcoes';
