/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dias da semana em que a categoria estara disponivel
 */
export interface CategoriaDisponibilidadeDto {

  /**
   * Disponivel aos domingos
   */
  domingo?: boolean;

  /**
   * Disponivel as quartas-feiras
   */
  quarta?: boolean;

  /**
   * Disponivel as quintas-feiras
   */
  quinta?: boolean;

  /**
   * Disponivel aos sabados
   */
  sabado?: boolean;

  /**
   * Disponivel as segundas-feiras
   */
  segunda?: boolean;

  /**
   * Disponivel as sextas-feiras
   */
  sexta?: boolean;

  /**
   * Disponivel as tercas-feiras
   */
  terca?: boolean;
}
