/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados de saida do endereco do cliente
 */
export interface ClienteEnderecoOutput {

  /**
   * Bairro
   */
  bairro?: string;

  /**
   * CEP
   */
  cep?: string;

  /**
   * Nome da cidade
   */
  cidade?: string;

  /**
   * Complemento
   */
  complemento?: string;

  /**
   * ID do endereco
   */
  id: number;

  /**
   * Codigo IBGE do municipio
   */
  municipio: number;

  /**
   * Numero
   */
  num?: string;

  /**
   * Ponto de referencia
   */
  ponto_referencia?: string;

  /**
   * Rua/Logradouro
   */
  rua?: string;

  /**
   * Sigla da UF
   */
  uf?: string;
}
