/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados de entrada para endereco do cliente
 */
export interface ClienteEnderecoInput {

  /**
   * Bairro
   */
  bairro?: string;

  /**
   * CEP
   */
  cep?: string;

  /**
   * Complemento
   */
  complemento?: string;

  /**
   * ID do endereco (informar apenas para atualizacao)
   */
  id?: number;

  /**
   * Codigo IBGE do municipio
   */
  municipio: number;

  /**
   * Numero
   */
  num?: string;

  /**
   * Ponto de referencia
   */
  ponto_referencia?: string;

  /**
   * Rua/Logradouro
   */
  rua?: string;
}
