/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para login
 */
export interface LoginInput {

  /**
   * Email do usuario
   */
  email: string;

  /**
   * Senha do usuario
   */
  senha: string;
}
