/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados de uma tentativa de login
 */
export interface LoginAttemptOutput {

  /**
   * Data e hora da tentativa
   */
  dataTentativa?: string;

  /**
   * ID da tentativa
   */
  id?: number;

  /**
   * Endereco IP de origem
   */
  ipAddress?: string;

  /**
   * Motivo da falha (se aplicavel)
   */
  motivoFalha?: string;

  /**
   * Se o login foi bem sucedido
   */
  sucesso?: boolean;

  /**
   * User Agent do navegador/cliente
   */
  userAgent?: string;
}
