/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requisicao para confirmar login via magic link
 */
export interface MagicLinkConfirmInput {

  /**
   * Token JWT recebido no magic link
   */
  token: string;
}
