/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MediaOutput {
  contentType?: string;
  createdAt?: string;
  filename?: string;
  id?: string;
  ownerId?: number;
  ownerType?: string;
  size?: number;
  url?: string;
}
