/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados de saida do Municipio
 */
export interface MunicipioOutput {

  /**
   * Codigo IBGE do Municipio
   */
  codigo: number;

  /**
   * Nome do Municipio
   */
  nome: string;
}
