/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Preco do produto
 */
export interface ProdutoPrecoOutput {

  /**
   * ID da opcao de categoria
   */
  id_opcao?: number;

  /**
   * ID do preco do produto
   */
  id_preco?: number;

  /**
   * Nome da opcao
   */
  nome?: string;

  /**
   * Status do preco (ativo/inativo)
   */
  status?: boolean;

  /**
   * Valor atribuido ao produto para esta opcao
   */
  valor?: number;
}
