/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados de saida da UF
 */
export interface UfOutput {

  /**
   * Codigo IBGE da UF
   */
  codigo: number;

  /**
   * Nome da UF
   */
  nome: string;

  /**
   * Sigla da UF
   */
  sigla: string;
}
