/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para atualizar um usuario
 */
export interface UserUpdateInput {

  /**
   * Email do usuario
   */
  email: string;

  /**
   * Nome completo do usuario
   */
  nome: string;
}
