/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para alterar o papel do usuario
 */
export interface UserRoleUpdateInput {

  /**
   * Novo papel do usuario (ADMIN ou MEMBER)
   */
  role: 'OWNER' | 'ADMIN' | 'MEMBER';
}
