/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Resposta com senha temporaria gerada
 */
export interface UserPasswordResetOutput {

  /**
   * Mensagem informativa
   */
  mensagem?: string;

  /**
   * Senha temporaria gerada (mostrar apenas uma vez)
   */
  senhaTemporaria?: string;

  /**
   * ID do usuario
   */
  userId?: number;
}
