/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados completos do usuario para administracao
 */
export interface UserAdminOutput {

  /**
   * Se o usuario esta ativo
   */
  ativo?: boolean;

  /**
   * URL do avatar do usuario
   */
  avatar?: string;

  /**
   * Se a conta esta bloqueada
   */
  contaBloqueada?: boolean;

  /**
   * Data de criacao do usuario
   */
  dataCriacao?: string;

  /**
   * Email do usuario
   */
  email?: string;

  /**
   * ID do usuario
   */
  id?: number;

  /**
   * Nome do usuario
   */
  nome?: string;

  /**
   * Papel do usuario na organizacao
   */
  role?: 'OWNER' | 'ADMIN' | 'MEMBER';

  /**
   * Se a senha esta expirada (precisa trocar)
   */
  senhaExpirada?: boolean;

  /**
   * Numero de tentativas de login falhas
   */
  tentativasFalha?: number;

  /**
   * Data do ultimo acesso
   */
  ultimoAcesso?: string;
}
