/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para criar um novo usuario
 */
export interface UserAdminInput {

  /**
   * Email do usuario
   */
  email: string;

  /**
   * Nome completo do usuario
   */
  nome: string;

  /**
   * Papel do usuario na organizacao
   */
  role: 'OWNER' | 'ADMIN' | 'MEMBER';
}
