/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAdminOutput } from '../../models/user-admin-output';
import { UserUpdateInput } from '../../models/user-update-input';

export interface Atualizar3$Params {

/**
 * ID do usuario
 */
  userId: number;
      body: UserUpdateInput
}

export function atualizar3(http: HttpClient, rootUrl: string, params: Atualizar3$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAdminOutput>> {
  const rb = new RequestBuilder(rootUrl, atualizar3.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAdminOutput>;
    })
  );
}

atualizar3.PATH = '/api/admin/users/{userId}';
