/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAdminOutput } from '../../models/user-admin-output';

export interface DesbloquearConta$Params {

/**
 * ID do usuario
 */
  userId: number;
}

export function desbloquearConta(http: HttpClient, rootUrl: string, params: DesbloquearConta$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAdminOutput>> {
  const rb = new RequestBuilder(rootUrl, desbloquearConta.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAdminOutput>;
    })
  );
}

desbloquearConta.PATH = '/api/admin/users/{userId}/unlock';
