/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginAttemptOutput } from '../../models/login-attempt-output';

export interface HistoricoLogin$Params {

/**
 * ID do usuario
 */
  userId: number;
}

export function historicoLogin(http: HttpClient, rootUrl: string, params: HistoricoLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LoginAttemptOutput>>> {
  const rb = new RequestBuilder(rootUrl, historicoLogin.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LoginAttemptOutput>>;
    })
  );
}

historicoLogin.PATH = '/api/admin/users/{userId}/login-history';
