/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageUserAdminOutput } from '../../models/page-user-admin-output';

export interface Listar1$Params {

/**
 * Filtrar por status ativo
 */
  ativo?: boolean;

/**
 * Filtrar por papel (ADMIN, MEMBER)
 */
  role?: string;

/**
 * Buscar por nome ou email
 */
  search?: string;

/**
 * Numero da pagina (0-based)
 */
  page?: number;

/**
 * Tamanho da pagina
 */
  size?: number;

/**
 * Ordenacao (campo,direcao)
 */
  sort?: string;
}

export function listar1(http: HttpClient, rootUrl: string, params?: Listar1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageUserAdminOutput>> {
  const rb = new RequestBuilder(rootUrl, listar1.PATH, 'get');
  if (params) {
    rb.query('ativo', params.ativo, {});
    rb.query('role', params.role, {});
    rb.query('search', params.search, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageUserAdminOutput>;
    })
  );
}

listar1.PATH = '/api/admin/users';
