/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAdminOutput } from '../../models/user-admin-output';

export interface Buscar4$Params {

/**
 * ID do usuario
 */
  userId: number;
}

export function buscar4(http: HttpClient, rootUrl: string, params: Buscar4$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAdminOutput>> {
  const rb = new RequestBuilder(rootUrl, buscar4.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAdminOutput>;
    })
  );
}

buscar4.PATH = '/api/admin/users/{userId}';
