/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProdutoInput } from '../../models/produto-input';
import { ProdutoOutput } from '../../models/produto-output';

export interface Criar1$Params {
      body: ProdutoInput
}

export function criar1(http: HttpClient, rootUrl: string, params: Criar1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProdutoOutput>> {
  const rb = new RequestBuilder(rootUrl, criar1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProdutoOutput>;
    })
  );
}

criar1.PATH = '/api/produtos';
