/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipOutput } from '../models/membership-output';
import { UserOutput } from '../models/user-output';

/**
 * Resposta de autenticacao com tokens e dados do usuario
 */
export interface AuthResponse {

  /**
   * Access token JWT (curta duracao)
   */
  accessToken: string;

  /**
   * Tempo de expiracao do access token em segundos
   */
  expiresIn: number;

  /**
   * Organizacoes do usuario
   */
  organizations: Array<MembershipOutput>;

  /**
   * Refresh token (longa duracao)
   */
  refreshToken: string;

  /**
   * Tipo do token
   */
  tokenType: string;

  /**
   * Dados do usuario autenticado
   */
  user: UserOutput;
}
