/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganizationOutput } from '../models/organization-output';

/**
 * Dados de membership do usuario em uma organizacao
 */
export interface MembershipOutput {

  /**
   * Dados da organizacao
   */
  organization?: OrganizationOutput;

  /**
   * Papel do usuario na organizacao
   */
  role?: 'OWNER' | 'ADMIN' | 'MEMBER';
}
