/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados da organizacao
 */
export interface OrganizationOutput {

  /**
   * ID da organizacao
   */
  id: number;

  /**
   * URL do logo da organizacao
   */
  logo?: string;

  /**
   * Nome da organizacao
   */
  nome: string;

  /**
   * Slug da organizacao (URL-friendly)
   */
  slug: string;
}
