/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para renovacao de token
 */
export interface RefreshTokenInput {

  /**
   * Refresh token atual
   */
  refreshToken: string;
}
