/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para registro de novo usuario
 */
export interface RegisterInput {

  /**
   * Email do usuario
   */
  email: string;

  /**
   * Nome completo do usuario
   */
  nome: string;

  /**
   * Nome da organizacao inicial (opcional)
   */
  nomeOrganizacao?: string;

  /**
   * Senha do usuario (minimo 6 caracteres)
   */
  senha: string;
}
