/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados do usuario
 */
export interface UserOutput {

  /**
   * Email do usuario
   */
  email?: string;

  /**
   * ID do usuario
   */
  id?: number;

  /**
   * Nome do usuario
   */
  nome?: string;
}
