-- Criação da tabela TODO
CREATE TABLE TODO (
    TODO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TODO_TITULO TEXT NOT NULL,
    TODO_DESCRICAO TEXT,
    TODO_CONCLUIDO INTEGER DEFAULT 0,
    TODO_DATA_CRIACAO TEXT NOT NULL,
    TODO_DATA_CONCLUSAO TEXT
);

-- Índice para busca por status
CREATE INDEX IDX_TODO_CONCLUIDO ON TODO(TODO_CONCLUIDO);

-- Índice para ordenação por data de criação
CREATE INDEX IDX_TODO_DATA_CRIACAO ON TODO(TODO_DATA_CRIACAO DESC);
