-- =============================================
-- Migration V0006: Criar tabela de arquivos armazenados (StoredFile)
-- =============================================

CREATE TABLE STORED_FILE (
    FILE_ID TEXT PRIMARY KEY,
    ORG_ID INTEGER NOT NULL,
    OWNER_TYPE TEXT NOT NULL,
    OWNER_ID INTEGER,
    FILE_NAME TEXT NOT NULL,
    CONTENT_TYPE TEXT,
    FILE_SIZE INTEGER,
    STORAGE_KEY TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    CREATED_BY INTEGER,
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_STORED_FILE_ORG ON STORED_FILE(ORG_ID);
CREATE INDEX IDX_STORED_FILE_OWNER ON STORED_FILE(OWNER_TYPE, OWNER_ID);
