-- =============================================
-- Migration V0004: Criar tabela de historico de login
-- =============================================

-- Tabela de Tentativas de Login
CREATE TABLE LOGIN_ATTEMPT (
    LGA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LGA_USR_ID INTEGER NOT NULL,
    LGA_SUCESSO INTEGER NOT NULL,
    LGA_IP_ADDRESS TEXT,
    LGA_USER_AGENT TEXT,
    LGA_MOTIVO_FALHA TEXT,
    LGA_DATA_TENTATIVA TEXT NOT NULL,
    FOREIGN KEY (LGA_USR_ID) REFERENCES USUARIO(USR_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_LGA_USR ON LOGIN_ATTEMPT(LGA_USR_ID);
CREATE INDEX IDX_LGA_DATA ON LOGIN_ATTEMPT(LGA_DATA_TENTATIVA);

-- Adicionar coluna de senha expirada na tabela ACCOUNT
ALTER TABLE ACCOUNT ADD COLUMN ACC_SENHA_EXPIRADA INTEGER DEFAULT 0;
