-- =============================================
-- Migration V0009: Criar tabelas de CATEGORIA e CATEGORIA_OPCAO
-- Estrutura multi-tenant (por ORGANIZATION) com soft delete (campo ATIVO)
-- =============================================

-- Tabela de categorias de produtos por organizacao
CREATE TABLE CATEGORIA (
    CAT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CAT_ORG_ID INTEGER NOT NULL,
    CAT_CUL_ID INTEGER NOT NULL,
    CAT_ORDEM INTEGER,
    CAT_NOME TEXT NOT NULL,
    CAT_DESCRICAO TEXT,
    CAT_INICIO TEXT,
    CAT_FIM TEXT,
    CAT_ATIVO INTEGER NOT NULL DEFAULT 1,
    CAT_OPCAO_MEIA TEXT NOT NULL DEFAULT '',
    CAT_DISP_DOMINGO INTEGER NOT NULL DEFAULT 1,
    CAT_DISP_SEGUNDA INTEGER NOT NULL DEFAULT 1,
    CAT_DISP_TERCA INTEGER NOT NULL DEFAULT 1,
    CAT_DISP_QUARTA INTEGER NOT NULL DEFAULT 1,
    CAT_DISP_QUINTA INTEGER NOT NULL DEFAULT 1,
    CAT_DISP_SEXTA INTEGER NOT NULL DEFAULT 1,
    CAT_DISP_SABADO INTEGER NOT NULL DEFAULT 1,
    CAT_DATA_CRIACAO TEXT NOT NULL,
    CAT_DATA_ATUALIZACAO TEXT,
    CAT_CRIADO_POR INTEGER,
    CONSTRAINT FK_CATEGORIA_ORGANIZATION
        FOREIGN KEY (CAT_ORG_ID) REFERENCES ORGANIZATION(ORG_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_CATEGORIA_CULINARIA
        FOREIGN KEY (CAT_CUL_ID) REFERENCES CULINARIA(CUL_ID),
    CONSTRAINT FK_CATEGORIA_CRIADO_POR
        FOREIGN KEY (CAT_CRIADO_POR) REFERENCES USUARIO(USR_ID)
        ON DELETE SET NULL,
    CONSTRAINT CK_CATEGORIA_OPCAO_MEIA
        CHECK (CAT_OPCAO_MEIA IN ('', 'M', 'V')),
    CONSTRAINT CK_CATEGORIA_HORARIO
        CHECK (CAT_INICIO IS NULL OR CAT_FIM IS NOT NULL)
);

-- Unicidade da ordem por organizacao (permite NULL)
CREATE UNIQUE INDEX IDX_CATEGORIA_ORG_ORDEM
    ON CATEGORIA(CAT_ORG_ID, CAT_ORDEM);

-- Indices auxiliares
CREATE INDEX IDX_CATEGORIA_ORG_ATIVO
    ON CATEGORIA(CAT_ORG_ID, CAT_ATIVO);

CREATE INDEX IDX_CATEGORIA_ORG_CULINARIA
    ON CATEGORIA(CAT_ORG_ID, CAT_CUL_ID);

-- Tabela de opcoes de categoria
CREATE TABLE CATEGORIA_OPCAO (
    CATOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CATOP_CAT_ID INTEGER NOT NULL,
    CATOP_NOME TEXT NOT NULL,
    CATOP_ATIVO INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT FK_CATEGORIA_OPCAO_CATEGORIA
        FOREIGN KEY (CATOP_CAT_ID) REFERENCES CATEGORIA(CAT_ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_CATEGORIA_OPCAO_CATEGORIA
    ON CATEGORIA_OPCAO(CATOP_CAT_ID, CATOP_ATIVO);

