-- =============================================
-- Migration V0011: Criar tabelas de ADICIONAL e ADICIONAL_ITEM
-- =============================================

-- Tabela de grupos de adicionais
CREATE TABLE ADICIONAL (
    ADC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ADC_ORG_ID INTEGER NOT NULL,
    ADC_CAT_ID INTEGER NOT NULL,
    ADC_NOME TEXT NOT NULL,
    ADC_SELECAO TEXT NOT NULL CHECK (ADC_SELECAO IN ('U','M','Q')),
    ADC_MINIMO INTEGER,
    ADC_LIMITE INTEGER,
    ADC_ATIVO INTEGER NOT NULL DEFAULT 1,
    ADC_DATA_CRIACAO TEXT NOT NULL,
    ADC_DATA_ATUALIZACAO TEXT,
    ADC_CRIADO_POR INTEGER,
    CONSTRAINT FK_ADC_ORG FOREIGN KEY (ADC_ORG_ID) REFERENCES ORGANIZATION(ORG_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ADC_CAT FOREIGN KEY (ADC_CAT_ID) REFERENCES CATEGORIA(CAT_ID),
    CONSTRAINT FK_ADC_CRIADO_POR FOREIGN KEY (ADC_CRIADO_POR) REFERENCES USUARIO(USR_ID) ON DELETE SET NULL
);

CREATE INDEX IDX_ADC_ORG_ATIVO ON ADICIONAL(ADC_ORG_ID, ADC_ATIVO);
CREATE INDEX IDX_ADC_ORG_CAT_ATIVO ON ADICIONAL(ADC_ORG_ID, ADC_CAT_ID, ADC_ATIVO);

-- Tabela de itens de adicionais
CREATE TABLE ADICIONAL_ITEM (
    AIT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AIT_ORG_ID INTEGER NOT NULL,
    AIT_ADC_ID INTEGER NOT NULL,
    AIT_NOME TEXT NOT NULL,
    AIT_VALOR NUMERIC(10,2) NOT NULL,
    AIT_ATIVO INTEGER NOT NULL DEFAULT 1,
    AIT_DATA_CRIACAO TEXT NOT NULL,
    AIT_DATA_ATUALIZACAO TEXT,
    CONSTRAINT FK_AIT_ORG FOREIGN KEY (AIT_ORG_ID) REFERENCES ORGANIZATION(ORG_ID) ON DELETE CASCADE,
    CONSTRAINT FK_AIT_ADC FOREIGN KEY (AIT_ADC_ID) REFERENCES ADICIONAL(ADC_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_AIT_ORG_ADC_ATIVO ON ADICIONAL_ITEM(AIT_ORG_ID, AIT_ADC_ID, AIT_ATIVO);

-- Trigger: ao desativar uma categoria, desativar adicionais e itens
CREATE TRIGGER TRG_CATEGORIA_SOFTDELETE_ADICIONAL
AFTER UPDATE ON CATEGORIA
WHEN OLD.CAT_ATIVO = 1 AND NEW.CAT_ATIVO = 0
BEGIN
    UPDATE ADICIONAL
    SET ADC_ATIVO = 0,
        ADC_DATA_ATUALIZACAO = datetime('now')
    WHERE ADC_CAT_ID = NEW.CAT_ID AND ADC_ORG_ID = NEW.CAT_ORG_ID;

    UPDATE ADICIONAL_ITEM
    SET AIT_ATIVO = 0,
        AIT_DATA_ATUALIZACAO = datetime('now')
    WHERE AIT_ADC_ID IN (SELECT ADC_ID FROM ADICIONAL WHERE ADC_CAT_ID = NEW.CAT_ID AND ADC_ORG_ID = NEW.CAT_ORG_ID);
END;

-- Trigger: ao desativar um adicional, desativar itens relacionados
CREATE TRIGGER TRG_ADC_SOFTDELETE_ITENS
AFTER UPDATE ON ADICIONAL
WHEN OLD.ADC_ATIVO = 1 AND NEW.ADC_ATIVO = 0
BEGIN
    UPDATE ADICIONAL_ITEM
    SET AIT_ATIVO = 0,
        AIT_DATA_ATUALIZACAO = datetime('now')
    WHERE AIT_ADC_ID = NEW.ADC_ID AND AIT_ORG_ID = NEW.ADC_ORG_ID;
END;

-- Trigger: garantir que item pertence ao mesmo org do adicional
CREATE TRIGGER TRG_AIT_VALIDATE_ORG
BEFORE INSERT ON ADICIONAL_ITEM
BEGIN
    SELECT
        CASE
            WHEN (
                SELECT ADC_ORG_ID FROM ADICIONAL WHERE ADC_ID = NEW.AIT_ADC_ID
            ) IS NOT NULL AND (
                SELECT ADC_ORG_ID FROM ADICIONAL WHERE ADC_ID = NEW.AIT_ADC_ID
            ) != NEW.AIT_ORG_ID
            THEN RAISE(ABORT, 'Organizacao do item deve ser a mesma do adicional')
        END;
END;

