-- =====================================================
-- V0013 - Criar tabelas CLIENTE e CLIENTE_ENDERECO
-- Data: 2025-11-30
-- Descricao: Cria tabelas de clientes e seus enderecos
--            com multi-tenancy e soft delete
-- =====================================================

-- -----------------------------------------------------
-- Tabela CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE (
    CLI_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CLI_ORG_ID INTEGER NOT NULL,
    CLI_NOME VARCHAR(200) NOT NULL,
    CLI_TEL_1 VARCHAR(20),
    CLI_TEL_2 VARCHAR(20),
    CLI_TEL_3 VARCHAR(20),
    CLI_DOCUMENTO VARCHAR(20),
    CLI_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CLI_DATA_CRIACAO DATETIME NOT NULL,
    CLI_DATA_ATUALIZACAO DATETIME,
    CLI_CRIADO_POR INTEGER,
    CONSTRAINT FK_CLIENTE_ORG FOREIGN KEY (CLI_ORG_ID) REFERENCES ORGANIZATION(ORG_ID)
);

-- Indices para CLIENTE
CREATE INDEX IF NOT EXISTS IDX_CLIENTE_ORG ON CLIENTE(CLI_ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_CLIENTE_DOCUMENTO ON CLIENTE(CLI_DOCUMENTO, CLI_ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_CLIENTE_ATIVO ON CLIENTE(CLI_ORG_ID, CLI_ATIVO);

-- -----------------------------------------------------
-- Tabela CLIENTE_ENDERECO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE_ENDERECO (
    END_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    END_CLI_ID INTEGER NOT NULL,
    END_ORG_ID INTEGER NOT NULL,
    END_MUNI_CD INTEGER NOT NULL,
    END_CEP VARCHAR(10),
    END_BAIRRO VARCHAR(100),
    END_RUA VARCHAR(200),
    END_NUM VARCHAR(20),
    END_COMPLEMENTO VARCHAR(100),
    END_PONTO_REFERENCIA VARCHAR(200),
    END_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    END_DATA_CRIACAO DATETIME NOT NULL,
    END_DATA_ATUALIZACAO DATETIME,
    CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (END_CLI_ID) REFERENCES CLIENTE(CLI_ID),
    CONSTRAINT FK_ENDERECO_ORG FOREIGN KEY (END_ORG_ID) REFERENCES ORGANIZATION(ORG_ID),
    CONSTRAINT FK_ENDERECO_MUNICIPIO FOREIGN KEY (END_MUNI_CD) REFERENCES MUNICIPIO(MUNI_CD)
);

-- Indices para CLIENTE_ENDERECO
CREATE INDEX IF NOT EXISTS IDX_ENDERECO_CLIENTE ON CLIENTE_ENDERECO(END_CLI_ID);
CREATE INDEX IF NOT EXISTS IDX_ENDERECO_ORG ON CLIENTE_ENDERECO(END_ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_ENDERECO_MUNICIPIO ON CLIENTE_ENDERECO(END_MUNI_CD);
CREATE INDEX IF NOT EXISTS IDX_ENDERECO_ATIVO ON CLIENTE_ENDERECO(END_CLI_ID, END_ATIVO);
