-- =============================================
-- Migration V0010: Criar tabelas de PRODUTO e PRODUTO_PRECO
-- =============================================

-- Tabela de produtos
CREATE TABLE PRODUTO (
    PRD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRD_ORG_ID INTEGER NOT NULL,
    PRD_CAT_ID INTEGER NOT NULL,
    PRD_NOME TEXT NOT NULL,
    PRD_DESCRICAO TEXT,
    PRD_ATIVO INTEGER NOT NULL DEFAULT 1,
    PRD_DATA_CRIACAO TEXT NOT NULL,
    PRD_DATA_ATUALIZACAO TEXT,
    PRD_CRIADO_POR INTEGER,
    CONSTRAINT FK_PROD_ORG FOREIGN KEY (PRD_ORG_ID) REFERENCES ORGANIZATION(ORG_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (PRD_CAT_ID) REFERENCES CATEGORIA(CAT_ID),
    CONSTRAINT FK_PROD_CRIADO_POR FOREIGN KEY (PRD_CRIADO_POR) REFERENCES USUARIO(USR_ID) ON DELETE SET NULL
);

CREATE INDEX IDX_PROD_ORG_ATIVO ON PRODUTO(PRD_ORG_ID, PRD_ATIVO);
CREATE INDEX IDX_PROD_ORG_CAT ON PRODUTO(PRD_ORG_ID, PRD_CAT_ID, PRD_ATIVO);

-- Tabela de precos dos produtos
CREATE TABLE PRODUTO_PRECO (
    PRP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRP_ORG_ID INTEGER NOT NULL,
    PRP_PRD_ID INTEGER NOT NULL,
    PRP_CATOP_ID INTEGER NOT NULL,
    PRP_VALOR NUMERIC(10,2) NOT NULL,
    PRP_ATIVO INTEGER NOT NULL DEFAULT 1,
    PRP_DATA_CRIACAO TEXT NOT NULL,
    PRP_DATA_ATUALIZACAO TEXT,
    CONSTRAINT FK_PRP_ORG FOREIGN KEY (PRP_ORG_ID) REFERENCES ORGANIZATION(ORG_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRP_PRD FOREIGN KEY (PRP_PRD_ID) REFERENCES PRODUTO(PRD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRP_CATOP FOREIGN KEY (PRP_CATOP_ID) REFERENCES CATEGORIA_OPCAO(CATOP_ID)
);

CREATE INDEX IDX_PRP_ORG_PRD_ATIVO ON PRODUTO_PRECO(PRP_ORG_ID, PRP_PRD_ID, PRP_ATIVO);
CREATE INDEX IDX_PRP_ORG_CATOP ON PRODUTO_PRECO(PRP_ORG_ID, PRP_CATOP_ID, PRP_ATIVO);

-- Trigger: ao desativar uma categoria, desativar produtos e precos relacionados
CREATE TRIGGER TRG_CATEGORIA_SOFTDELETE_PRODUTO
AFTER UPDATE ON CATEGORIA
WHEN OLD.CAT_ATIVO = 1 AND NEW.CAT_ATIVO = 0
BEGIN
    UPDATE PRODUTO
    SET PRD_ATIVO = 0,
        PRD_DATA_ATUALIZACAO = datetime('now')
    WHERE PRD_CAT_ID = NEW.CAT_ID;

    UPDATE PRODUTO_PRECO
    SET PRP_ATIVO = 0,
        PRP_DATA_ATUALIZACAO = datetime('now')
    WHERE PRP_PRD_ID IN (SELECT PRD_ID FROM PRODUTO WHERE PRD_CAT_ID = NEW.CAT_ID);
END;

-- Trigger: ao desativar uma opcao de categoria, desativar precos relacionados
CREATE TRIGGER TRG_CATOP_SOFTDELETE_PRECO
AFTER UPDATE ON CATEGORIA_OPCAO
WHEN OLD.CATOP_ATIVO = 1 AND NEW.CATOP_ATIVO = 0
BEGIN
    UPDATE PRODUTO_PRECO
    SET PRP_ATIVO = 0,
        PRP_DATA_ATUALIZACAO = datetime('now')
    WHERE PRP_CATOP_ID = NEW.CATOP_ID;
END;

-- Trigger: impedir preco com opcao de categoria diferente da categoria do produto
CREATE TRIGGER TRG_PRP_VALIDATE_CAT
BEFORE INSERT ON PRODUTO_PRECO
BEGIN
    SELECT
        CASE
            WHEN (
                SELECT CAT_ID FROM CATEGORIA_OPCAO CO
                JOIN CATEGORIA C ON C.CAT_ID = CO.CATOP_CAT_ID
                JOIN PRODUTO P ON P.PRD_ID = NEW.PRP_PRD_ID
                WHERE CO.CATOP_ID = NEW.PRP_CATOP_ID
                LIMIT 1
            ) IS NULL OR (
                SELECT C2.CAT_ID FROM CATEGORIA_OPCAO CO2
                JOIN CATEGORIA C2 ON C2.CAT_ID = CO2.CATOP_CAT_ID
                JOIN PRODUTO P2 ON P2.PRD_ID = NEW.PRP_PRD_ID
                WHERE CO2.CATOP_ID = NEW.PRP_CATOP_ID
                LIMIT 1
            ) <> (SELECT PRD_CAT_ID FROM PRODUTO WHERE PRD_ID = NEW.PRP_PRD_ID)
            THEN RAISE(ABORT, 'Opcao de categoria nao pertence a categoria do produto')
        END;
END;

