/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MembershipOutput } from '../../models/membership-output';
import { OrganizationInput } from '../../models/organization-input';

export interface Criar2$Params {
      body: OrganizationInput
}

export function criar2(http: HttpClient, rootUrl: string, params: Criar2$Params, context?: HttpContext): Observable<StrictHttpResponse<MembershipOutput>> {
  const rb = new RequestBuilder(rootUrl, criar2.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MembershipOutput>;
    })
  );
}

criar2.PATH = '/api/organizations';
