/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoOutput } from '../../models/todo-output';

export interface Buscar$Params {

/**
 * ID da tarefa
 */
  id: number;
}

export function buscar(http: HttpClient, rootUrl: string, params: Buscar$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoOutput>> {
  const rb = new RequestBuilder(rootUrl, buscar.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoOutput>;
    })
  );
}

buscar.PATH = '/api/todos/{id}';
