/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoOutput } from '../../models/todo-output';

export interface Listar$Params {

/**
 * Filtrar por status de conclusão (true = concluídas, false = pendentes)
 */
  concluido?: boolean;
}

export function listar(http: HttpClient, rootUrl: string, params?: Listar$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TodoOutput>>> {
  const rb = new RequestBuilder(rootUrl, listar.PATH, 'get');
  if (params) {
    rb.query('concluido', params.concluido, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TodoOutput>>;
    })
  );
}

listar.PATH = '/api/todos';
