/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoOutput } from '../../models/todo-output';

export interface Reabrir$Params {

/**
 * ID da tarefa
 */
  id: number;
}

export function reabrir(http: HttpClient, rootUrl: string, params: Reabrir$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoOutput>> {
  const rb = new RequestBuilder(rootUrl, reabrir.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoOutput>;
    })
  );
}

reabrir.PATH = '/api/todos/{id}/reabrir';
