/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Opcao de adicional
 */
export interface AdicionalOpcaoInput {

  /**
   * Nome do adicional
   */
  nome: string;

  /**
   * Status do adicional (ativo/inativo)
   */
  status?: boolean;

  /**
   * Preco do adicional
   */
  valor: number;
}
