/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Item de adicional
 */
export interface AdicionalItemOutput {

  /**
   * ID do item de adicional
   */
  id_item?: number;

  /**
   * Nome do adicional
   */
  nome?: string;

  /**
   * Status (ativo/inativo)
   */
  status?: boolean;

  /**
   * Valor do adicional
   */
  valor?: number;
}
