/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClienteEnderecoInput {
  id?: number;
  municipio: number;
  cep?: string;
  bairro?: string;
  rua?: string;
  num?: string;
  complemento?: string;
  ponto_referencia?: string;
}
