/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClienteEnderecoOutput {
  id: number;
  cep?: string;
  municipio: number;
  uf?: string;
  cidade?: string;
  bairro?: string;
  rua?: string;
  num?: string;
  complemento?: string;
  ponto_referencia?: string;
}
