/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requisicao para login via magic link
 */
export interface MagicLinkLoginInput {

  /**
   * Email do usuario que recebera o magic link
   */
  email: string;
}
