/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para criar uma nova organizacao
 */
export interface OrganizationInput {

  /**
   * Nome da organizacao
   */
  nome: string;
}
