/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Opcao de preco do produto
 */
export interface ProdutoOpcaoInput {

  /**
   * ID da opcao de categoria
   */
  id_opcao: number;

  /**
   * Preco atribuido ao produto para esta opcao
   */
  valor: number;
}
