/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados da tarefa
 */
export interface TodoInput {

  /**
   * Descrição detalhada da tarefa
   */
  descricao?: string;

  /**
   * Título da tarefa
   */
  titulo: string;
}
