-- =============================================
-- Migration V0002: Criar tabelas de autenticacao
-- =============================================

-- Tabela de Organizacoes
CREATE TABLE ORGANIZATION (
    ORG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ORG_NOME TEXT NOT NULL,
    ORG_SLUG TEXT NOT NULL UNIQUE,
    ORG_LOGO TEXT,
    ORG_ATIVA INTEGER DEFAULT 1,
    ORG_DATA_CRIACAO TEXT NOT NULL,
    ORG_DATA_ATUALIZACAO TEXT
);

CREATE INDEX IDX_ORG_SLUG ON ORGANIZATION(ORG_SLUG);
CREATE INDEX IDX_ORG_ATIVA ON ORGANIZATION(ORG_ATIVA);

-- Tabela de Usuarios
CREATE TABLE USUARIO (
    USR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USR_NOME TEXT NOT NULL,
    USR_EMAIL TEXT NOT NULL UNIQUE,
    USR_ATIVO INTEGER DEFAULT 1,
    USR_DATA_CRIACAO TEXT NOT NULL,
    USR_DATA_ATUALIZACAO TEXT,
    USR_ULTIMO_ACESSO TEXT
);

CREATE INDEX IDX_USR_EMAIL ON USUARIO(USR_EMAIL);
CREATE INDEX IDX_USR_ATIVO ON USUARIO(USR_ATIVO);

-- Tabela de Memberships (relacionamento Usuario-Organizacao com papel)
CREATE TABLE MEMBERSHIP (
    MBR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MBR_USR_ID INTEGER NOT NULL,
    MBR_ORG_ID INTEGER NOT NULL,
    MBR_PAPEL TEXT NOT NULL DEFAULT 'MEMBER',
    MBR_ATIVO INTEGER DEFAULT 1,
    MBR_DATA_INGRESSO TEXT NOT NULL,
    MBR_CONVIDADO_POR INTEGER,
    FOREIGN KEY (MBR_USR_ID) REFERENCES USUARIO(USR_ID) ON DELETE CASCADE,
    FOREIGN KEY (MBR_ORG_ID) REFERENCES ORGANIZATION(ORG_ID) ON DELETE CASCADE,
    UNIQUE(MBR_USR_ID, MBR_ORG_ID)
);

CREATE INDEX IDX_MBR_USR ON MEMBERSHIP(MBR_USR_ID);
CREATE INDEX IDX_MBR_ORG ON MEMBERSHIP(MBR_ORG_ID);
CREATE INDEX IDX_MBR_PAPEL ON MEMBERSHIP(MBR_PAPEL);

-- Tabela de Contas (credenciais de autenticacao)
CREATE TABLE ACCOUNT (
    ACC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACC_USR_ID INTEGER NOT NULL,
    ACC_PROVIDER TEXT NOT NULL DEFAULT 'local',
    ACC_SENHA_HASH TEXT,
    ACC_BLOQUEADO INTEGER DEFAULT 0,
    ACC_TENTATIVAS_FALHA INTEGER DEFAULT 0,
    ACC_DATA_BLOQUEIO TEXT,
    ACC_DATA_CRIACAO TEXT NOT NULL,
    ACC_DATA_ALTERACAO_SENHA TEXT,
    FOREIGN KEY (ACC_USR_ID) REFERENCES USUARIO(USR_ID) ON DELETE CASCADE,
    UNIQUE(ACC_USR_ID, ACC_PROVIDER)
);

CREATE INDEX IDX_ACC_USR ON ACCOUNT(ACC_USR_ID);
CREATE INDEX IDX_ACC_PROVIDER ON ACCOUNT(ACC_PROVIDER);

-- Tabela de Refresh Tokens (armazenamento seguro)
CREATE TABLE REFRESH_TOKEN (
    RT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RT_TOKEN_HASH TEXT NOT NULL UNIQUE,
    RT_USR_ID INTEGER NOT NULL,
    RT_DATA_EXPIRACAO TEXT NOT NULL,
    RT_DATA_CRIACAO TEXT NOT NULL,
    RT_REVOGADO INTEGER DEFAULT 0,
    RT_DATA_REVOGACAO TEXT,
    RT_FAMILIA_ID TEXT NOT NULL,
    RT_DEVICE_INFO TEXT,
    RT_IP_ADDRESS TEXT,
    FOREIGN KEY (RT_USR_ID) REFERENCES USUARIO(USR_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_RT_TOKEN ON REFRESH_TOKEN(RT_TOKEN_HASH);
CREATE INDEX IDX_RT_USR ON REFRESH_TOKEN(RT_USR_ID);
CREATE INDEX IDX_RT_FAMILIA ON REFRESH_TOKEN(RT_FAMILIA_ID);
CREATE INDEX IDX_RT_REVOGADO ON REFRESH_TOKEN(RT_REVOGADO);
