/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MunicipioOutput } from '../../models/municipio-output';

export interface ListarTodosMunicipios$Params {
}

export function listarTodosMunicipios(http: HttpClient, rootUrl: string, params?: ListarTodosMunicipios$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MunicipioOutput>>> {
  const rb = new RequestBuilder(rootUrl, listarTodosMunicipios.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MunicipioOutput>>;
    })
  );
}

listarTodosMunicipios.PATH = '/api/dados-abertos/municipios';
