/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClienteInput } from '../../models/cliente-input';
import { ClienteOutput } from '../../models/cliente-output';

export interface Criar6$Params {
  body: ClienteInput;
}

export function criar6(http: HttpClient, rootUrl: string, params: Criar6$Params, context?: HttpContext): Observable<StrictHttpResponse<ClienteOutput>> {
  const rb = new RequestBuilder(rootUrl, criar6.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClienteOutput>;
    })
  );
}

criar6.PATH = '/api/clientes';
