/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserOutput } from '../../models/user-output';

export interface AtualizarAvatar1$Params {
      body?: {

/**
 * Arquivo de avatar (PNG/JPEG/WEBP)
 */
'file': Blob;
}
}

export function atualizarAvatar1(http: HttpClient, rootUrl: string, params?: AtualizarAvatar1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserOutput>> {
  const rb = new RequestBuilder(rootUrl, atualizarAvatar1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserOutput>;
    })
  );
}

atualizarAvatar1.PATH = '/api/account/avatar';
