/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MediaOutput } from '../../models/media-output';

export interface Upload$Params {

/**
 * Tipo do dono do arquivo
 */
  ownerType: 'ORGANIZATION' | 'USER' | 'PRODUCT' | 'OTHER';

/**
 * ID do dono do arquivo (pode ser nulo para uso generico)
 */
  ownerId?: number;
      body?: {

/**
 * Arquivo a ser enviado
 */
'file': Blob;
}
}

export function upload(http: HttpClient, rootUrl: string, params: Upload$Params, context?: HttpContext): Observable<StrictHttpResponse<MediaOutput>> {
  const rb = new RequestBuilder(rootUrl, upload.PATH, 'post');
  if (params) {
    rb.query('ownerType', params.ownerType, {});
    rb.query('ownerId', params.ownerId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MediaOutput>;
    })
  );
}

upload.PATH = '/api/media';
