/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProdutoOutput } from '../../models/produto-output';

export interface Buscar1$Params {
  id: number;
}

export function buscar1(http: HttpClient, rootUrl: string, params: Buscar1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProdutoOutput>> {
  const rb = new RequestBuilder(rootUrl, buscar1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProdutoOutput>;
    })
  );
}

buscar1.PATH = '/api/produtos/{id}';
