/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProdutoOutput } from '../../models/produto-output';

export interface Listar1$Params {

/**
 * ID da categoria para filtrar
 */
  id_categoria?: number;
}

export function listar1(http: HttpClient, rootUrl: string, params?: Listar1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProdutoOutput>>> {
  const rb = new RequestBuilder(rootUrl, listar1.PATH, 'get');
  if (params) {
    rb.query('id_categoria', params.id_categoria, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProdutoOutput>>;
    })
  );
}

listar1.PATH = '/api/produtos';
