/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdicionalOutput } from '../../models/adicional-output';

export interface Listar5$Params {

/**
 * ID da categoria (opcional)
 */
  id_categoria?: number;
}

export function listar5(http: HttpClient, rootUrl: string, params?: Listar5$Params, context?: HttpContext): Observable<StrictHttpResponse<AdicionalOutput>> {
  const rb = new RequestBuilder(rootUrl, listar5.PATH, 'get');
  if (params) {
    rb.query('id_categoria', params.id_categoria, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/problem+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdicionalOutput>;
    })
  );
}

listar5.PATH = '/api/adicionais';
