/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaOpcaoInput } from '../../models/categoria-opcao-input';
import { CategoriaOpcaoOutput } from '../../models/categoria-opcao-output';

export interface AdicionarOpcao$Params {

/**
 * ID da categoria
 */
  idCategoria: number;
      body: CategoriaOpcaoInput
}

export function adicionarOpcao(http: HttpClient, rootUrl: string, params: AdicionarOpcao$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaOpcaoOutput>> {
  const rb = new RequestBuilder(rootUrl, adicionarOpcao.PATH, 'post');
  if (params) {
    rb.path('idCategoria', params.idCategoria, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaOpcaoOutput>;
    })
  );
}

adicionarOpcao.PATH = '/api/categorias/{idCategoria}/opcoes';
