/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaOpcaoInput } from '../../models/categoria-opcao-input';
import { CategoriaOpcaoOutput } from '../../models/categoria-opcao-output';

export interface AtualizarOpcao$Params {

/**
 * ID da categoria
 */
  idCategoria: number;

/**
 * ID da opcao
 */
  idOpcao: number;
      body: CategoriaOpcaoInput
}

export function atualizarOpcao(http: HttpClient, rootUrl: string, params: AtualizarOpcao$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaOpcaoOutput>> {
  const rb = new RequestBuilder(rootUrl, atualizarOpcao.PATH, 'put');
  if (params) {
    rb.path('idCategoria', params.idCategoria, {});
    rb.path('idOpcao', params.idOpcao, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaOpcaoOutput>;
    })
  );
}

atualizarOpcao.PATH = '/api/categorias/{idCategoria}/opcoes/{idOpcao}';
