/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaInput } from '../../models/categoria-input';
import { CategoriaOutput } from '../../models/categoria-output';

export interface Atualizar4$Params {

/**
 * ID da categoria
 */
  id: number;
      body: CategoriaInput
}

export function atualizar4(http: HttpClient, rootUrl: string, params: Atualizar4$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaOutput>> {
  const rb = new RequestBuilder(rootUrl, atualizar4.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaOutput>;
    })
  );
}

atualizar4.PATH = '/api/categorias/{id}';
