/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaInput } from '../../models/categoria-input';
import { CategoriaOutput } from '../../models/categoria-output';

export interface Criar4$Params {
      body: CategoriaInput
}

export function criar4(http: HttpClient, rootUrl: string, params: Criar4$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaOutput>> {
  const rb = new RequestBuilder(rootUrl, criar4.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaOutput>;
    })
  );
}

criar4.PATH = '/api/categorias';
