/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoInput } from '../../models/todo-input';
import { TodoOutput } from '../../models/todo-output';

export interface Criar$Params {
      body: TodoInput
}

export function criar(http: HttpClient, rootUrl: string, params: Criar$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoOutput>> {
  const rb = new RequestBuilder(rootUrl, criar.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoOutput>;
    })
  );
}

criar.PATH = '/api/todos';
