/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CulinariaOutput } from '../../models/culinaria-output';

export interface Listar5$Params {
  meioMeio?: boolean;
}

export function listar5(http: HttpClient, rootUrl: string, params?: Listar5$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CulinariaOutput>>> {
  const rb = new RequestBuilder(rootUrl, listar5.PATH, 'get');
  if (params) {
    rb.query('meioMeio', params.meioMeio, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CulinariaOutput>>;
    })
  );
}

listar5.PATH = '/api/culinarias';
