/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrganizationInput } from '../../models/organization-input';
import { OrganizationOutput } from '../../models/organization-output';

export interface Atualizar1$Params {

/**
 * ID da organizacao
 */
  id: number;
      body: OrganizationInput
}

export function atualizar1(http: HttpClient, rootUrl: string, params: Atualizar1$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganizationOutput>> {
  const rb = new RequestBuilder(rootUrl, atualizar1.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrganizationOutput>;
    })
  );
}

atualizar1.PATH = '/api/organizations/{id}';
